### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by ericscrum** [CS193A/How-To#11]
## Enrollment request
Eric Cramer
emcramer@stanford.edu

**Comment by dddutz** [comment]
It seems like you haven't accepted the CS193A organization invitation yet. Please go to https://github.com/CS193A

**Comment by dddutz** [comment]
In order to properly process your assignments and for you to take part in peer grading, you must join the CS193A organization. It seems like you haven't accepted the invitation yet. Please accept it by going to https://github.com/CS193A.

**Comment by ericscrum** [comment]
How exactly do I accept the invitation? Is there an option to do so at that URL?

**Comment by dddutz** [comment]
Simply going to https://github.com/CS193A should accept the invitation. Otherwise, there should be a link there to view and accept the invitation. If neither of those work, you should be able to accept the invitation from the first email invite I sent you. Let me know if none of those work or if you have any other questions!
